version: "3.9"
services:
  postgres:
    image: postgres:15-alpine
    container_name: acueducto-postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./acueducto-backend
    container_name: acueducto-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: nestuser
      DB_PASS: nestpass
      DB_NAME: nestdb
    command: >
      sh -c "
        ./wait-for-it.sh postgres:5432 -- 
        npm run start:dev
      "
    volumes:
      - ./acueducto-backend:/usr/src/app
    ports:
      - "3000:3000"
  frontend:
    platform: linux/arm64
    build:
      context: ./acueducto-frontend
      dockerfile: Dockerfile
    container_name: acueducto-frontend
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      PORT: 3001
    volumes:
      - ./acueducto-frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    command: npm run dev

volumes:
  postgres_data:
