version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: acueducto-postgres
    restart: always
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: nestdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./acueducto-backend
    container_name: acueducto-backend
    restart: always
    env_file:
      - ./acueducto-backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  frontend:
    build: ./acueducto-frontend
    container_name: acueducto-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
